version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: biblioteca-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
